Reintroduce PR limit
heroku/heroku-buildpack-ruby pull request #1249
Opened 2021-12-16 17:06 UTC by schneems

When multiple PRs are opened concurrently multiple tests are fired off. These all compete for the same API limits. Hatchet has baked in rate limiter. When it runs out of API requests, it will slow down. If too many concurrent CI executions are kicked off at one time, all the builds slow one another down, and prevent any of them from completing.

2021-12-16 18:35 UTC, edmorley requested changes
Can we try raising the limits instead? The raised limits for Python's CI user have been working fine (and by raised I mean 50x multiplier not 5x, plus a raised max apps count). I'll apply those same changes to Ruby now.

2021-12-16 19:02 UTC, edmorley commented
With raised limits these concurrent runs all passed:
![Screenshot](https://user-images.githubusercontent.com/501702/146432593-a418ca1e-cfbe-42a9-87a3-e748641c9b8b.png)

2022-01-03 17:23 UTC, schneems commented
> Can we try raising the limits instead?

The last time I spoke to web services (years ago) they told me very firmly to not raise them higher than 5. It has been quite some time, but there was once an incident triggered due to buildpack tests in logplex as buildpack tests use services in ways that customers generally won't. It might be safer to raise the limit now, but I would want to ask them before doing it.

In general, I actually don't like these PRs to the Ruby buildpack. None of the dependencies we use in production and Ruby tends to have many patch releases in many components that just aren't that critical in dev. It ends up being a lot of toil. 

Even when we get X concurrent PRs we have to rebase X times so it doesn't really help that much due to the requirement that PRs be up to date.

I appreciate you staying on top of the PRs, but it's not a value add task to this repo (other than Hatchet and generally I do that manually as I'm typically dogfooding a fix). I'm happy to talk about this more.

2022-01-03 22:12 UTC, edmorley approved these changes

2022-01-04 15:53 UTC, merged