Remove circle tests
heroku/heroku-buildpack-ruby pull request #1326
Opened 2022-10-31 16:01 UTC by schneems

GUS-W-11832774

2022-10-31 16:25 UTC, edmorley reviewed
What are your thoughts about also deleting this no-longer-run CNB spec?
https://github.com/heroku/heroku-buildpack-ruby/blob/main/spec/cnb/basic_local_pack_spec.rb

I know the buildpack still has basic CNB support, but leaving this CNB test around without running it means it'll get out of date/break anyway, plus potentially cause confusion for people looking at the repo working out what tests are actually used/run. Should you ever need to refer to the CNB tests they'll still exist in the Git log.

If that spec was deleted, the following can also be cleaned up:
- the `--exclude-pattern` here:
https://github.com/heroku/heroku-buildpack-ruby/blob/83da2a7651f97b5354900144a57d6c5c53862269/app.json#L23
- the cutlass usages in `spec/spec_helper.rb`
- the cutlass dependency can be dropped

2022-10-31 16:37 UTC, edmorley commented
The existing Heroku CI tests are also failing:
https://dashboard.heroku.com/pipelines/ac057663-170b-4bdd-99d0-87560eb3a570/tests/1728

2022-11-07 22:05 UTC, schneems commented
@edmorley updated, tests are now passing. They were failing due to the stack image default change.

2022-11-08 08:58 UTC, edmorley requested changes

2022-11-08 08:58 UTC, edmorley commented on spec/cnb/basic_local_pack_spec.rb
> -
With this spec removed, the following are unused and can also be removed:
- the cutlass usages in `spec/spec_helper.rb`
- the cutlass dependency can be dropped

(Mentioned in the last review: https://github.com/heroku/heroku-buildpack-ruby/pull/1326#pullrequestreview-1162175333)

2022-11-08 18:45 UTC, edmorley approved these changes
Looks great - thank you!

2022-11-08 18:54 UTC, merged